// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket_purchase.proto

// Protobuf Java Version: 3.25.1
package edu.upb.tmservice.grpc;

public interface CompraTicketRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tmservice.CompraTicketRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id_usuario = 1;</code>
   * @return The idUsuario.
   */
  long getIdUsuario();

  /**
   * <code>int64 id_evento = 2;</code>
   * @return The idEvento.
   */
  long getIdEvento();

  /**
   * <code>int64 id_tipo_ticket = 3;</code>
   * @return The idTipoTicket.
   */
  long getIdTipoTicket();

  /**
   * <code>int32 cantidad = 4;</code>
   * @return The cantidad.
   */
  int getCantidad();

  /**
   * <code>string idempotency_key = 5;</code>
   * @return The idempotencyKey.
   */
  java.lang.String getIdempotencyKey();
  /**
   * <code>string idempotency_key = 5;</code>
   * @return The bytes for idempotencyKey.
   */
  com.google.protobuf.ByteString
      getIdempotencyKeyBytes();
}
