// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket_purchase.proto

// Protobuf Java Version: 3.25.1
package edu.upb.tmservice.grpc;

/**
 * Protobuf type {@code tmservice.CompraTicketRequest}
 */
public final class CompraTicketRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tmservice.CompraTicketRequest)
    CompraTicketRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompraTicketRequest.newBuilder() to construct.
  private CompraTicketRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompraTicketRequest() {
    idempotencyKey_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CompraTicketRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.upb.tmservice.grpc.CompraTicketRequest.class, edu.upb.tmservice.grpc.CompraTicketRequest.Builder.class);
  }

  public static final int ID_USUARIO_FIELD_NUMBER = 1;
  private long idUsuario_ = 0L;
  /**
   * <code>int64 id_usuario = 1;</code>
   * @return The idUsuario.
   */
  @java.lang.Override
  public long getIdUsuario() {
    return idUsuario_;
  }

  public static final int ID_EVENTO_FIELD_NUMBER = 2;
  private long idEvento_ = 0L;
  /**
   * <code>int64 id_evento = 2;</code>
   * @return The idEvento.
   */
  @java.lang.Override
  public long getIdEvento() {
    return idEvento_;
  }

  public static final int ID_TIPO_TICKET_FIELD_NUMBER = 3;
  private long idTipoTicket_ = 0L;
  /**
   * <code>int64 id_tipo_ticket = 3;</code>
   * @return The idTipoTicket.
   */
  @java.lang.Override
  public long getIdTipoTicket() {
    return idTipoTicket_;
  }

  public static final int CANTIDAD_FIELD_NUMBER = 4;
  private int cantidad_ = 0;
  /**
   * <code>int32 cantidad = 4;</code>
   * @return The cantidad.
   */
  @java.lang.Override
  public int getCantidad() {
    return cantidad_;
  }

  public static final int IDEMPOTENCY_KEY_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object idempotencyKey_ = "";
  /**
   * <code>string idempotency_key = 5;</code>
   * @return The idempotencyKey.
   */
  @java.lang.Override
  public java.lang.String getIdempotencyKey() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idempotencyKey_ = s;
      return s;
    }
  }
  /**
   * <code>string idempotency_key = 5;</code>
   * @return The bytes for idempotencyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdempotencyKeyBytes() {
    java.lang.Object ref = idempotencyKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idempotencyKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (idUsuario_ != 0L) {
      output.writeInt64(1, idUsuario_);
    }
    if (idEvento_ != 0L) {
      output.writeInt64(2, idEvento_);
    }
    if (idTipoTicket_ != 0L) {
      output.writeInt64(3, idTipoTicket_);
    }
    if (cantidad_ != 0) {
      output.writeInt32(4, cantidad_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idempotencyKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, idempotencyKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (idUsuario_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, idUsuario_);
    }
    if (idEvento_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, idEvento_);
    }
    if (idTipoTicket_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, idTipoTicket_);
    }
    if (cantidad_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, cantidad_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idempotencyKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, idempotencyKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.upb.tmservice.grpc.CompraTicketRequest)) {
      return super.equals(obj);
    }
    edu.upb.tmservice.grpc.CompraTicketRequest other = (edu.upb.tmservice.grpc.CompraTicketRequest) obj;

    if (getIdUsuario()
        != other.getIdUsuario()) return false;
    if (getIdEvento()
        != other.getIdEvento()) return false;
    if (getIdTipoTicket()
        != other.getIdTipoTicket()) return false;
    if (getCantidad()
        != other.getCantidad()) return false;
    if (!getIdempotencyKey()
        .equals(other.getIdempotencyKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_USUARIO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdUsuario());
    hash = (37 * hash) + ID_EVENTO_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdEvento());
    hash = (37 * hash) + ID_TIPO_TICKET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdTipoTicket());
    hash = (37 * hash) + CANTIDAD_FIELD_NUMBER;
    hash = (53 * hash) + getCantidad();
    hash = (37 * hash) + IDEMPOTENCY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getIdempotencyKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static edu.upb.tmservice.grpc.CompraTicketRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static edu.upb.tmservice.grpc.CompraTicketRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.upb.tmservice.grpc.CompraTicketRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.upb.tmservice.grpc.CompraTicketRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tmservice.CompraTicketRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tmservice.CompraTicketRequest)
      edu.upb.tmservice.grpc.CompraTicketRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.upb.tmservice.grpc.CompraTicketRequest.class, edu.upb.tmservice.grpc.CompraTicketRequest.Builder.class);
    }

    // Construct using edu.upb.tmservice.grpc.CompraTicketRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      idUsuario_ = 0L;
      idEvento_ = 0L;
      idTipoTicket_ = 0L;
      cantidad_ = 0;
      idempotencyKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketRequest_descriptor;
    }

    @java.lang.Override
    public edu.upb.tmservice.grpc.CompraTicketRequest getDefaultInstanceForType() {
      return edu.upb.tmservice.grpc.CompraTicketRequest.getDefaultInstance();
    }

    @java.lang.Override
    public edu.upb.tmservice.grpc.CompraTicketRequest build() {
      edu.upb.tmservice.grpc.CompraTicketRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.upb.tmservice.grpc.CompraTicketRequest buildPartial() {
      edu.upb.tmservice.grpc.CompraTicketRequest result = new edu.upb.tmservice.grpc.CompraTicketRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(edu.upb.tmservice.grpc.CompraTicketRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.idUsuario_ = idUsuario_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.idEvento_ = idEvento_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.idTipoTicket_ = idTipoTicket_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cantidad_ = cantidad_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.idempotencyKey_ = idempotencyKey_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.upb.tmservice.grpc.CompraTicketRequest) {
        return mergeFrom((edu.upb.tmservice.grpc.CompraTicketRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.upb.tmservice.grpc.CompraTicketRequest other) {
      if (other == edu.upb.tmservice.grpc.CompraTicketRequest.getDefaultInstance()) return this;
      if (other.getIdUsuario() != 0L) {
        setIdUsuario(other.getIdUsuario());
      }
      if (other.getIdEvento() != 0L) {
        setIdEvento(other.getIdEvento());
      }
      if (other.getIdTipoTicket() != 0L) {
        setIdTipoTicket(other.getIdTipoTicket());
      }
      if (other.getCantidad() != 0) {
        setCantidad(other.getCantidad());
      }
      if (!other.getIdempotencyKey().isEmpty()) {
        idempotencyKey_ = other.idempotencyKey_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              idUsuario_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              idEvento_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              idTipoTicket_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              cantidad_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              idempotencyKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long idUsuario_ ;
    /**
     * <code>int64 id_usuario = 1;</code>
     * @return The idUsuario.
     */
    @java.lang.Override
    public long getIdUsuario() {
      return idUsuario_;
    }
    /**
     * <code>int64 id_usuario = 1;</code>
     * @param value The idUsuario to set.
     * @return This builder for chaining.
     */
    public Builder setIdUsuario(long value) {

      idUsuario_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id_usuario = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdUsuario() {
      bitField0_ = (bitField0_ & ~0x00000001);
      idUsuario_ = 0L;
      onChanged();
      return this;
    }

    private long idEvento_ ;
    /**
     * <code>int64 id_evento = 2;</code>
     * @return The idEvento.
     */
    @java.lang.Override
    public long getIdEvento() {
      return idEvento_;
    }
    /**
     * <code>int64 id_evento = 2;</code>
     * @param value The idEvento to set.
     * @return This builder for chaining.
     */
    public Builder setIdEvento(long value) {

      idEvento_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id_evento = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdEvento() {
      bitField0_ = (bitField0_ & ~0x00000002);
      idEvento_ = 0L;
      onChanged();
      return this;
    }

    private long idTipoTicket_ ;
    /**
     * <code>int64 id_tipo_ticket = 3;</code>
     * @return The idTipoTicket.
     */
    @java.lang.Override
    public long getIdTipoTicket() {
      return idTipoTicket_;
    }
    /**
     * <code>int64 id_tipo_ticket = 3;</code>
     * @param value The idTipoTicket to set.
     * @return This builder for chaining.
     */
    public Builder setIdTipoTicket(long value) {

      idTipoTicket_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id_tipo_ticket = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdTipoTicket() {
      bitField0_ = (bitField0_ & ~0x00000004);
      idTipoTicket_ = 0L;
      onChanged();
      return this;
    }

    private int cantidad_ ;
    /**
     * <code>int32 cantidad = 4;</code>
     * @return The cantidad.
     */
    @java.lang.Override
    public int getCantidad() {
      return cantidad_;
    }
    /**
     * <code>int32 cantidad = 4;</code>
     * @param value The cantidad to set.
     * @return This builder for chaining.
     */
    public Builder setCantidad(int value) {

      cantidad_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cantidad = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCantidad() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cantidad_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object idempotencyKey_ = "";
    /**
     * <code>string idempotency_key = 5;</code>
     * @return The idempotencyKey.
     */
    public java.lang.String getIdempotencyKey() {
      java.lang.Object ref = idempotencyKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idempotencyKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idempotency_key = 5;</code>
     * @return The bytes for idempotencyKey.
     */
    public com.google.protobuf.ByteString
        getIdempotencyKeyBytes() {
      java.lang.Object ref = idempotencyKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idempotencyKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idempotency_key = 5;</code>
     * @param value The idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      idempotencyKey_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string idempotency_key = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdempotencyKey() {
      idempotencyKey_ = getDefaultInstance().getIdempotencyKey();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string idempotency_key = 5;</code>
     * @param value The bytes for idempotencyKey to set.
     * @return This builder for chaining.
     */
    public Builder setIdempotencyKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      idempotencyKey_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tmservice.CompraTicketRequest)
  }

  // @@protoc_insertion_point(class_scope:tmservice.CompraTicketRequest)
  private static final edu.upb.tmservice.grpc.CompraTicketRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.upb.tmservice.grpc.CompraTicketRequest();
  }

  public static edu.upb.tmservice.grpc.CompraTicketRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompraTicketRequest>
      PARSER = new com.google.protobuf.AbstractParser<CompraTicketRequest>() {
    @java.lang.Override
    public CompraTicketRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CompraTicketRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompraTicketRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.upb.tmservice.grpc.CompraTicketRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

