// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket_purchase.proto

// Protobuf Java Version: 3.25.1
package edu.upb.tmservice.grpc;

public interface CompraTicketResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tmservice.CompraTicketResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 primer_ticket_id = 1;</code>
   * @return The primerTicketId.
   */
  long getPrimerTicketId();

  /**
   * <code>int32 tickets_creados = 2;</code>
   * @return The ticketsCreados.
   */
  int getTicketsCreados();

  /**
   * <code>string status = 3;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string mensaje = 4;</code>
   * @return The mensaje.
   */
  java.lang.String getMensaje();
  /**
   * <code>string mensaje = 4;</code>
   * @return The bytes for mensaje.
   */
  com.google.protobuf.ByteString
      getMensajeBytes();
}
