// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket_purchase.proto

// Protobuf Java Version: 3.25.1
package edu.upb.tmservice.grpc;

/**
 * Protobuf type {@code tmservice.CompraTicketResponse}
 */
public final class CompraTicketResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tmservice.CompraTicketResponse)
    CompraTicketResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompraTicketResponse.newBuilder() to construct.
  private CompraTicketResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompraTicketResponse() {
    status_ = "";
    mensaje_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CompraTicketResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            edu.upb.tmservice.grpc.CompraTicketResponse.class, edu.upb.tmservice.grpc.CompraTicketResponse.Builder.class);
  }

  public static final int PRIMER_TICKET_ID_FIELD_NUMBER = 1;
  private long primerTicketId_ = 0L;
  /**
   * <code>int64 primer_ticket_id = 1;</code>
   * @return The primerTicketId.
   */
  @java.lang.Override
  public long getPrimerTicketId() {
    return primerTicketId_;
  }

  public static final int TICKETS_CREADOS_FIELD_NUMBER = 2;
  private int ticketsCreados_ = 0;
  /**
   * <code>int32 tickets_creados = 2;</code>
   * @return The ticketsCreados.
   */
  @java.lang.Override
  public int getTicketsCreados() {
    return ticketsCreados_;
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 3;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MENSAJE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mensaje_ = "";
  /**
   * <code>string mensaje = 4;</code>
   * @return The mensaje.
   */
  @java.lang.Override
  public java.lang.String getMensaje() {
    java.lang.Object ref = mensaje_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mensaje_ = s;
      return s;
    }
  }
  /**
   * <code>string mensaje = 4;</code>
   * @return The bytes for mensaje.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMensajeBytes() {
    java.lang.Object ref = mensaje_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mensaje_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (primerTicketId_ != 0L) {
      output.writeInt64(1, primerTicketId_);
    }
    if (ticketsCreados_ != 0) {
      output.writeInt32(2, ticketsCreados_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensaje_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, mensaje_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (primerTicketId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, primerTicketId_);
    }
    if (ticketsCreados_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, ticketsCreados_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mensaje_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, mensaje_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof edu.upb.tmservice.grpc.CompraTicketResponse)) {
      return super.equals(obj);
    }
    edu.upb.tmservice.grpc.CompraTicketResponse other = (edu.upb.tmservice.grpc.CompraTicketResponse) obj;

    if (getPrimerTicketId()
        != other.getPrimerTicketId()) return false;
    if (getTicketsCreados()
        != other.getTicketsCreados()) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getMensaje()
        .equals(other.getMensaje())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PRIMER_TICKET_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPrimerTicketId());
    hash = (37 * hash) + TICKETS_CREADOS_FIELD_NUMBER;
    hash = (53 * hash) + getTicketsCreados();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + MENSAJE_FIELD_NUMBER;
    hash = (53 * hash) + getMensaje().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static edu.upb.tmservice.grpc.CompraTicketResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static edu.upb.tmservice.grpc.CompraTicketResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static edu.upb.tmservice.grpc.CompraTicketResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(edu.upb.tmservice.grpc.CompraTicketResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tmservice.CompraTicketResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tmservice.CompraTicketResponse)
      edu.upb.tmservice.grpc.CompraTicketResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.upb.tmservice.grpc.CompraTicketResponse.class, edu.upb.tmservice.grpc.CompraTicketResponse.Builder.class);
    }

    // Construct using edu.upb.tmservice.grpc.CompraTicketResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      primerTicketId_ = 0L;
      ticketsCreados_ = 0;
      status_ = "";
      mensaje_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return edu.upb.tmservice.grpc.TicketPurchase.internal_static_tmservice_CompraTicketResponse_descriptor;
    }

    @java.lang.Override
    public edu.upb.tmservice.grpc.CompraTicketResponse getDefaultInstanceForType() {
      return edu.upb.tmservice.grpc.CompraTicketResponse.getDefaultInstance();
    }

    @java.lang.Override
    public edu.upb.tmservice.grpc.CompraTicketResponse build() {
      edu.upb.tmservice.grpc.CompraTicketResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public edu.upb.tmservice.grpc.CompraTicketResponse buildPartial() {
      edu.upb.tmservice.grpc.CompraTicketResponse result = new edu.upb.tmservice.grpc.CompraTicketResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(edu.upb.tmservice.grpc.CompraTicketResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.primerTicketId_ = primerTicketId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ticketsCreados_ = ticketsCreados_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.mensaje_ = mensaje_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof edu.upb.tmservice.grpc.CompraTicketResponse) {
        return mergeFrom((edu.upb.tmservice.grpc.CompraTicketResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(edu.upb.tmservice.grpc.CompraTicketResponse other) {
      if (other == edu.upb.tmservice.grpc.CompraTicketResponse.getDefaultInstance()) return this;
      if (other.getPrimerTicketId() != 0L) {
        setPrimerTicketId(other.getPrimerTicketId());
      }
      if (other.getTicketsCreados() != 0) {
        setTicketsCreados(other.getTicketsCreados());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getMensaje().isEmpty()) {
        mensaje_ = other.mensaje_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              primerTicketId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              ticketsCreados_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              mensaje_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long primerTicketId_ ;
    /**
     * <code>int64 primer_ticket_id = 1;</code>
     * @return The primerTicketId.
     */
    @java.lang.Override
    public long getPrimerTicketId() {
      return primerTicketId_;
    }
    /**
     * <code>int64 primer_ticket_id = 1;</code>
     * @param value The primerTicketId to set.
     * @return This builder for chaining.
     */
    public Builder setPrimerTicketId(long value) {

      primerTicketId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 primer_ticket_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrimerTicketId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      primerTicketId_ = 0L;
      onChanged();
      return this;
    }

    private int ticketsCreados_ ;
    /**
     * <code>int32 tickets_creados = 2;</code>
     * @return The ticketsCreados.
     */
    @java.lang.Override
    public int getTicketsCreados() {
      return ticketsCreados_;
    }
    /**
     * <code>int32 tickets_creados = 2;</code>
     * @param value The ticketsCreados to set.
     * @return This builder for chaining.
     */
    public Builder setTicketsCreados(int value) {

      ticketsCreados_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 tickets_creados = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTicketsCreados() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ticketsCreados_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 3;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 3;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 3;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 3;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object mensaje_ = "";
    /**
     * <code>string mensaje = 4;</code>
     * @return The mensaje.
     */
    public java.lang.String getMensaje() {
      java.lang.Object ref = mensaje_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mensaje_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string mensaje = 4;</code>
     * @return The bytes for mensaje.
     */
    public com.google.protobuf.ByteString
        getMensajeBytes() {
      java.lang.Object ref = mensaje_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mensaje_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string mensaje = 4;</code>
     * @param value The mensaje to set.
     * @return This builder for chaining.
     */
    public Builder setMensaje(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mensaje_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string mensaje = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMensaje() {
      mensaje_ = getDefaultInstance().getMensaje();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string mensaje = 4;</code>
     * @param value The bytes for mensaje to set.
     * @return This builder for chaining.
     */
    public Builder setMensajeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mensaje_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tmservice.CompraTicketResponse)
  }

  // @@protoc_insertion_point(class_scope:tmservice.CompraTicketResponse)
  private static final edu.upb.tmservice.grpc.CompraTicketResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new edu.upb.tmservice.grpc.CompraTicketResponse();
  }

  public static edu.upb.tmservice.grpc.CompraTicketResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompraTicketResponse>
      PARSER = new com.google.protobuf.AbstractParser<CompraTicketResponse>() {
    @java.lang.Override
    public CompraTicketResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CompraTicketResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompraTicketResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public edu.upb.tmservice.grpc.CompraTicketResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

