// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ticket_purchase.proto

// Protobuf Java Version: 3.25.1
package edu.upb.tmservice.grpc;

public final class TicketPurchase {
  private TicketPurchase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tmservice_CompraTicketRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tmservice_CompraTicketRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tmservice_CompraTicketResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tmservice_CompraTicketResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025ticket_purchase.proto\022\ttmservice\"\177\n\023Co" +
      "mpraTicketRequest\022\022\n\nid_usuario\030\001 \001(\003\022\021\n" +
      "\tid_evento\030\002 \001(\003\022\026\n\016id_tipo_ticket\030\003 \001(\003" +
      "\022\020\n\010cantidad\030\004 \001(\005\022\027\n\017idempotency_key\030\005 " +
      "\001(\t\"j\n\024CompraTicketResponse\022\030\n\020primer_ti" +
      "cket_id\030\001 \001(\003\022\027\n\017tickets_creados\030\002 \001(\005\022\016" +
      "\n\006status\030\003 \001(\t\022\017\n\007mensaje\030\004 \001(\t2i\n\025Ticke" +
      "tPurchaseService\022P\n\rcomprarTicket\022\036.tmse" +
      "rvice.CompraTicketRequest\032\037.tmservice.Co" +
      "mpraTicketResponseB\032\n\026edu.upb.tmservice." +
      "grpcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tmservice_CompraTicketRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tmservice_CompraTicketRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tmservice_CompraTicketRequest_descriptor,
        new java.lang.String[] { "IdUsuario", "IdEvento", "IdTipoTicket", "Cantidad", "IdempotencyKey", });
    internal_static_tmservice_CompraTicketResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tmservice_CompraTicketResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tmservice_CompraTicketResponse_descriptor,
        new java.lang.String[] { "PrimerTicketId", "TicketsCreados", "Status", "Mensaje", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
